### ISSUE TITLE
Something wrong with the garment processing?

### ISSUE THREAD

**Issue by ParticleDog** [TemryL/ComfyUI-IDM-VTON#12]
When I use other clouthes than the default one, the output color always be dark, like below:
![image](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/125952123/5c60aa3f-ecbf-43b5-bc7b-6f7c87f1a285)

![image](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/125952123/2e5d598c-ecaa-4552-8887-44c936c187f2)

**Comment by TemryL** [comment]
Hi guys, yes it is a bug that needs to be fixed! I think it comes from the mask generation with SAM because in the demo the mask is much bigger and does not cover only the clothe but the whole upper body. One idea could be to try to load a manually generated mask and see what happens. If their is still a mismatch color, then probably the preprocessing of the images in the inference pipeline is wrong. Let me know if you can investigate on that. Thanks!

**Comment by TemryL** [comment]
Same problem described is [this issue](https://github.com/TemryL/ComfyUI-IDM-VTON/issues/13). I will close this one as duplicate.
